### ISSUE TITLE
RegisterGameServer.bat Run failed？Ask for help

### ISSUE THREAD

**Issue by fmpoffice** [PCasafont/L2T_Server#3]
[zip] Building zip: G:\l2qq\L2T_Server\build\L2Tenkai_Server.zip
BUILD SUCCESSFUL

Successful installation database and configurations for my computer，but Running  RegisterGameServer  is failed ！

`Exception in thread "main" java.lang.NoClassDefFoundError: l2server/gameserver/gui/ConsoleTab$ConsoleFilter
        at l2server.log.Log.info(Log.java:64)
        at l2server.Config.load(Config.java:1162)
        at l2server.gsregistering.BaseGameServerRegister.loadImp(BaseGameServerRegister.java:315)
        at l2server.gsregistering.BaseGameServerRegister.load(BaseGameServerRegister.java:296)
        at l2server.gsregistering.GameServerRegister.<init>(GameServerRegister.java:43)
        at l2server.gsregistering.BaseGameServerRegister.startCMD(BaseGameServerRegister.java:276)
        at l2server.gsregistering.BaseGameServerRegister.main(BaseGameServerRegister.java:192)
Caused by: java.lang.ClassNotFoundException: l2server.gameserver.gui.ConsoleTab$ConsoleFilter
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more`

**Comment by fmpoffice** [comment]
I have settled，Thank L2Tenkai
